# vim: ft=conf fdm=marker et sts=2 sw=2

# Don't bother to check SSL certificates.
--no-check-certificate

# Specify a custom user agent.
--user-agent 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36'

# Embed subtitles in the video.
--embed-subs

# Use aria2 as an external downloader.
--external-downloader aria2c

# Don't download videos with height higher that 1080p.
# If format selection isn't available, just get the best.
--format 'bestvideo[height<=?1080]+bestaudio/best[height<=?1080]/best'

# YouTube now requires JavaScript voodoo to download videos.
# yt-dlp recommends deno, but that's not available on the Debian repos.
--js-runtimes node
