#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# snipsort is a Python 3 script to sort the snippets in a given file
# alphabetically.  For more information, run
#
#   snipsort -h
#

import re
import argparse


def snipsort(file, inplace=False):
    """Sort all the snippets in a given file alphabetically."""
    name, contents = None, []
    snippets = {}

    with open(file, "r") as fd:
        for line in fd:
            if re.match(r"^(#|snippet)", line) and name:
                snippets[name] = contents
                name, contents = None, []

            match = re.match(r"^snippet\s+(.*)$", line)
            if match:
                name = match.group(1).strip()

            contents += [line.rstrip()]

    if name:
        snippets[name] = contents

    if inplace:
        with open(file, "w") as fd:
            for name in sorted(snippets.keys()):
                print("\n".join(snippets[name]), file=fd)
    else:
        for name in sorted(snippets.keys()):
            print("\n".join(snippets[name]))


if __name__ == "__main__":
    arg_parser = argparse.ArgumentParser(prog="snipsort",
        description="A script to sort snippets.")
    arg_parser.add_argument("-i", "--inplace", action="store_true",
        default=False, help="write files in place")
    arg_parser.add_argument("file", help="snippets file", nargs="+")
    args = arg_parser.parse_args()

    for file in args.file:
        snipsort(file, inplace=args.inplace)
