#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# NAME
#
#   snipsort - sort the snippets in a given file alphabetically
#
# SYNOPSIS
#
#   snipsort <file>...
#

import fileinput
import re

if __name__ == '__main__':
    name, contents = None, []
    snippets = {}

    with fileinput.input() as fd:
        for line in fd:
            if re.match(r"^(#|snippet)", line) and name:
                snippets[name] = contents
                name, contents = None, []

            match = re.match(r"^snippet\s+(.*)$", line)
            if match:
                name = match.group(1).strip()

            contents += [line.rstrip()]

    if name:
        snippets[name] = contents

    for name in sorted(snippets.keys()):
        for line in snippets[name]:
            print(line)
