SetOptions[$FrontEnd,
VersionsLaunched->{"12.1.0"},
PrivateFrontEndOptions->{"DialogSettings"->{
  "Login"->{"RememberMe"->True},
  "WelcomeScreen"->{"ShowRecentFilesContextMenu"->False}},
"LastRegistrationReminderDate"->None,
"ShowAtStartup"->"NewDocument",
"WolframAlphaSettings"->{"Autoload"->False}},
PrivateNotebookOptions->{"FinalWindowPrompt"->False},
ShowPredictiveInterface->False
]
