SetOptions[$FrontEnd,
VersionsLaunched->{"13.1.0"},
DefaultStyleDefinitions->"ReverseColor.nb",
PrivateFrontEndOptions->{"DialogSettings"->{
  "Login"->{"RememberMe"->True},
  "WelcomeScreen"->{"ShowRecentFilesContextMenu"->False}},
"LastRegistrationReminderDate"->None,
"ShowAtStartup"->"NewDocument",
"WolframAlphaSettings"->{"Autoload"->False, "SendMathematicaSessionInfo"->False}},
PrivateNotebookOptions->{"FinalWindowPrompt"->False},
CellContext->Notebook,
ShowPredictiveInterface->False,
TrackCellChangeTimes->False,
BlinkingCellInsertionPoint->False,
TabSpacings->{2.},
]
